
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Changing into source directory $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      - echo "need to install package to each lambda folder"
      - cd index-photos && pip install -r requirements.txt -t ./ 
      - cd ../Search_LF2 && pip install -r requirements.txt -t ./

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo "Build started on `date`"
      - echo "zip package and code to zip for each lambda"
      - cd index-photos && zip -r ../index-photos.zip *
      - cd $CODEBUILD_SRC_DIR
      - cd Search_LF2 && zip -r ../Search_LF2.zip *

  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo "deploy zip to labmda use aws cli"
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://index-photos.zip 
      - aws lambda update-function-code --function-name Search_LF2 --zip-file fileb://Search_LF2.zip
      - echo "upload zip to s3" 
      - aws s3 cp index-photos.zip  s3://xxzkbxx-lambda-zip/index-photos.zip
      - aws s3 cp Search_LF2.zip  s3://xxzkbxx-lambda-zip/Search_LF2.zip
artifacts:
  files:
    - index-photos.zip
